---
title: 'N Cycling Gene Prevalence'
subtitle: "Source file: Ncycling_genes.Rmd"
date: "`r Sys.Date()`"
output:
  html_document: 
    css: stylesheet.css
    fig_caption: yes
    number_sections: yes
    df_print: paged
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(vegan)
library(readxl)
library(latex2exp)
library(kableExtra)
library(tidyverse)
library(ggplot2)
library(readxl)
library(plotly)
library(knitr)
opts_knit$set(root.dir = ".", output_dir = file.path("documents"))
opts_chunk$set(
  dev=c("png", "pdf"), dev.args=list(pdf = list(encoding="WinAnsi", useDingbats=FALSE)),
  fig.keep="all")
source(file.path("scripts", "functions.R"))
```

## Import Data
```{r}
normalized_gene_abundance <- read_excel("data/NCycDB/Ncycling_normalized_geneabundances_95.xlsx")
```


## Dot plot
```{r}
#for plotting, create factor of gene names
normalized_gene_abundance$gene <-  factor(normalized_gene_abundance$gene, levels = c("nifD", "hdh", "hzsA", "hzo", "nxrB", "hao", "Bacterial amoA", "Archaeal amoA", "nrfA", "nosZ", "norB", "nirS", "nirK", "narG", "napA", "nirA", "nasA", "narB"))

#for plotting, create factor of N processes
normalized_gene_abundance$process <-  factor(normalized_gene_abundance$process, levels = c("Assimilatory nitrate reduction", "Dissimilatory nitrate reduction", "Denitrification", "DNRA", "Nitrification", "Annamox", "Nitrogen fixation"))

#gather data for plotting
dotplot_data <- normalized_gene_abundance %>%
  gather(well, normalized_abundance, `WAB103 2015`:`NSHQ14 (100m) 2017`) %>% mutate(
  	fluid_type = case_when(grepl("WAB55", well) ~ "Mg_HCO3", grepl("WAB56", well) ~ "Ca_OH", grepl("WAB71", well) ~ "Ca_OH", grepl("WAB104", well) ~ "Mg_HCO3", grepl("WAB105", well) ~ "Mg_HCO3", grepl("WAB103", well) ~ "gabbro", grepl("NSHQ3B", well) ~ "Mg_HCO3", grepl("WAB188", well) ~ "gabbro", grepl("NSHQ4", well) ~ "Ca_OH", grepl("NSHQ14", well) ~ "Ca_OH"))
  
#assign colors 	
colors_fluids_named <- c("gabbro" = "#669900", "Mg_HCO3" = "#33CCCC","Ca_OH" = "#330099")
 
#for plotting, assign factor for well names
dotplot_data$well <-  factor(dotplot_data$well, levels = c("NSHQ14 (100m) 2017", "NSHQ14 (55m) 2017", "NSHQ14 2015", "WAB71 2017", "WAB71 2015", "WAB56 2015", "NSHQ4 2017", "NSHQ4 2015", "WAB55 2017", "WAB55 2015", "WAB105 2017", "WAB104 2017", "NSHQ3B 2015", "WAB188 2017", "WAB188 2015", "WAB103 2015"))
#for plotting, assign factor for fluid type
dotplot_data$fluid_type <-  factor(dotplot_data$fluid_type, levels = unique(dotplot_data$fluid_type))
dotplot_data <- dotplot_data %>% mutate(
	well = fct_rev(well)
)

#change 0's to NA for plotting (otherwise small point will show up)
dotplot_data$normalized_abundance[dotplot_data$normalized_abundance== 0.00] <- NA

#plot
dotplot <- dotplot_data %>% 
		ggplot(
	aes(x = well, y = gene)) +
		geom_point(aes(color = process, size = normalized_abundance)) +
	scale_color_manual(values = c("#332288", "#882255", "#AA4499", "#88CCEE", "#117733", "#44BB99",  "#CC6677")) +
	geom_raster(aes(fill = fluid_type), alpha = .1)+
	scale_fill_manual(name = "Fluid Type", values = colors_fluids_named, labels = unname(latex2exp::TeX(c( "gabbro", "Mg$^{2+}$ - HCO$_{3}^{-}$", "Ca$^{2+}$ - OH$^{-}$")))) +
	theme_figure(grid = FALSE, text_size = 12) +
	theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
	theme(plot.background = element_rect(fill = "transparent")) +
	theme(axis.text.x = element_text(angle = 90, hjust = 1), axis.text.y = element_text(face = "italic"))+
	theme(axis.text=element_text(face="bold",size="12")) +
	theme(axis.title=element_text(face="bold",size= "16")) +
  xlab("Well") +
  ylab("Gene") +
	guides(size = guide_legend(title = "# of gene homologs/Mb sequence"), color = guide_legend(title = 'N-cycling Process'))

dotplot

#export 
ggsave("Figure_5.tiff", path = "figures/", width = 7.08661, height = 7.08661, device='tiff', bg='white', dpi=300)
```

